app:
    build: .
    command: flask run -h 0.0.0.0
    links:
        - redis
    ports:
        - 127.0.0.1:5000:5000
    environment:
        FLASK_DEBUG: 1
        SETTINGS: config.py
    volumes:
        - './config.py:/usr/src/app/config.py'

redis:
    image: redis
